version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"  # will use Directory.Packages.props
    schedule:
      interval: "weekly"
